spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:matchduo;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

  flyway:
    enabled: false

  mail:
    host: test
    port: 1010

custom:
  cookie:
    secure: false
    sameSite: Lax

riot:
  api:
    base-url: test
    key: test-mock-key

logging:
  level:
    root: WARN
    com.back.matchduo: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.web: WARN
    org.springframework.messaging: WARN
    com.zaxxer.hikari: WARN
